# Targets to acheieve 

latency: 10
speedIndex: 100
loadTime: 4
visualComplete: 500
speedScore: 50


# ENV Configurations
RUN_PERIODICALLY: false
RUN_PER_COMMIT: true

# PATH TO TEST
TEST_PATH: '/check'
